### ISSUE TITLE
nltk.tree is not a package

### ISSUE THREAD

**Issue by jsrozner** [Halvani/Constituent-Treelib#7]
Trying to run the example here:
[spacy.io/universe/project/constituent_treelib](https://spacy.io/universe/project/constituent_treelib)

`from constituent_treelib import ConstituentTree, Language`

Gives error ModuleNotFoundError: No module named 'nltk.tree.prettyprinter'; 'nltk.tree' is not a package

Looks like explore.py is importing
`from nltk.tree.prettyprinter import TreePrettyPrinter`
instead of
`from nltk.treeprettyprinter import TreePrettyPrinter`

Removing the dot fixes it

**Comment by Halvani** [comment]
Unit tests passed successfully after merging to the master branch. Closing the issue.
